# Generated by Django 5.2.1 on 2025-06-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='headline',
            field=models.CharField(blank=True, help_text='A short headline or summary of your professional profile', max_length=255, null=True),
        ),
    ]
