# Generated by Django 5.2.1 on 2025-06-05 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_jobseekerprofile_skills_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the certification', null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='document',
            field=models.FileField(blank=True, help_text='Upload the certification document', null=True, upload_to='certifications/'),
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='profiles.jobseekerprofile')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['candidate', 'viewed_at'], name='profiles_pr_candida_881826_idx'), models.Index(fields=['viewer', 'viewed_at'], name='profiles_pr_viewer__35a600_idx')],
            },
        ),
    ]
