# Generated by Django 5.2.1 on 2025-05-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('employer', 'Employer'), ('administrator', 'Administrator'), ('recruiter', 'Recruiter'), ('hr', 'HR')], default='candidate', max_length=100),
        ),
    ]
