# Generated by Django 5.2.1 on 2025-05-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options_alter_companymember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
